sudo: required
language: generic
services: 
    - docker

before_install:
    - docker build -t krc04/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true krc04/docker-react npm run test -- --coverage